title: BOC Currency Price
show_downloads: false
safe: true
url: https://bocurrencyprice.techina.science/
enforce_ssl: bocurrencyprice.techina.science
timezone: Asia/Shanghai
author: ZNing

plugins:
  - jekyll-feed

google_analytics: G-MTYH758FNF