name: 'Fetch currency price from BOC Actions'

on:
  # push:
  #   branches: ["main"]
  schedule:
    - cron: '*/25 * * * *'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout from repo
      uses: actions/checkout@main
      with:
        ref: main

    - name: Checkout private tools
      uses: actions/checkout@main
      with:
        repository: zning1994/boc_currency_price_tracker
        branch: main
        token: ${{ secrets.PRIVATE_TOEKEN }}
        path: scripts
    
    - name: Install Python latest
      uses: actions/setup-python@main
      with:
        python-version: '3.x'
        architecture: 'x64'

    - name: Install dependencies
      run: |
        if [ -f ./scripts/requirements.txt ]; then pip install -r ./scripts/requirements.txt; fi
 
    - name: Doing fetch and convert
      run: |
        cd scripts;
        python boc_currency_price.py AED
        python boc_currency_price.py USD
        python boc_currency_price.py EUR
        python boc_currency_price.py HKD
        python boc_currency_price.py GBP
        python boc_currency_price.py JPY
        python boc_currency_price.py SAR
        python generate_readme.py
        mv docs ../;

    - name: Commit files
      run: |
        git config --local user.email "zhn038@gmail.com"
        git config --local user.name "ZNing"
        git add .
        git commit -m "chore: update currency price $(date "+%Y-%m-%d %H:%M:%S")"
 
    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        branch: main
